name 'bootstrap_a_node'
maintainer 'Ryuji Goto'
maintainer_email 'r-goto@creationline.com'
license 'All Rights Reserved'
description 'Installs/Configures bootstrap_a_node'
version '3.0.0'
chef_version '>= 16.0'
depends 'slack_handler', '~> 1.0.0'
depends 'chef_client_updater', '~> 3.11.1'
depends 'chef-client', '~> 12.3.3'
